# SPDX-FileCopyrightText: 2025 TII (SSRC) and the Ghaf contributors
#
# SPDX-License-Identifier: Apache-2.0

# Checks that can run on github-hosted runners, and don't need secrets

name: check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install nix
        uses: cachix/install-nix-action@d1ca217b388ee87b2507a9a93bf01368bde7cec2 # v31
      - name: Check .nix formatting
        run: nix fmt -- --fail-on-change
      - name: Check reuse lint
        run: nix develop --command reuse lint
      - name: Check nix flake show runs successfully
        run: nix flake show --all-systems
  eval:
    runs-on: ubuntu-latest
    needs: [check]
    timeout-minutes: 360
    strategy:
      matrix:
        include:
          - jobid: 0
          - jobid: 1
    concurrency:
      # Cancel any in-progress workflow runs from the same PR or branch,
      # allowing matrix jobs to run concurrently:
      group: ${{ github.workflow }}.${{ github.event.pull_request.number || github.ref }}.${{ matrix.jobid }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install nix
        uses: cachix/install-nix-action@d1ca217b388ee87b2507a9a93bf01368bde7cec2 # v31
      - name: Evaluate (jobid=${{ matrix.jobid }})
        run: |
          echo "strategy.job-total: ${{ strategy.job-total }}"
          echo "matrix.jobid: ${{ matrix.jobid }}"
          nix develop --command .github/eval.sh -t '(devShells\.)' -j ${{ matrix.jobid }} -m ${{ strategy.job-total }}
