# SPDX-FileCopyrightText: 2022-2025 TII (SSRC) and the Ghaf contributors
#
# SPDX-License-Identifier: Apache-2.0

name: eval
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  eval:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    strategy:
      matrix:
        include:
          - jobid: 0
          - jobid: 1
          - jobid: 2
          - jobid: 3
    concurrency:
      # Cancel any in-progress workflow runs from the same PR or branch,
      # allowing matrix jobs to run concurrently:
      group: ${{ github.workflow }}.${{ github.event.pull_request.number || github.ref }}.${{ matrix.jobid }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install nix
        uses: cachix/install-nix-action@d1ca217b388ee87b2507a9a93bf01368bde7cec2 # v31
      - name: Evaluate (jobid=${{ matrix.jobid }})
        run: |
          echo "strategy.job-total: ${{ strategy.job-total }}"
          echo "matrix.jobid: ${{ matrix.jobid }}"
          nix develop --command .github/eval.sh -t '(devShells\.|packages\.)' -j ${{ matrix.jobid }} -m ${{ strategy.job-total }}
